
application:
  name: spring-ports-and-adapters-hexagonal-architecture
server:
  address: localhost
  port: 8080
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  sql:
    init:
      mode: always
#      schema-locations:
#        classpath: schema.sql
#      data-locations:
#        classpath: data.sql
  lifecycle:
    timeout-per-shutdown-phase: 1m
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'   # H2 DB ?? ?? (In-Memory Mode)
#    url: 'jdbc:h2:~/test'    # H2 DB ?? ?? (Embedded Mode)
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
#    defer-datasource-initialization: false

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true